/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NodeCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeCondition{}

// NodeCondition struct for NodeCondition
type NodeCondition struct {
	Condition Condition `json:"condition"`
	Status bool `json:"status"`
	Message NullableString `json:"message,omitempty"`
	LastHeartbeatAt time.Time `json:"last_heartbeat_at"`
	LastTransitionAt time.Time `json:"last_transition_at"`
}

type _NodeCondition NodeCondition

// NewNodeCondition instantiates a new NodeCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeCondition(condition Condition, status bool, lastHeartbeatAt time.Time, lastTransitionAt time.Time) *NodeCondition {
	this := NodeCondition{}
	this.Condition = condition
	this.Status = status
	this.LastHeartbeatAt = lastHeartbeatAt
	this.LastTransitionAt = lastTransitionAt
	return &this
}

// NewNodeConditionWithDefaults instantiates a new NodeCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeConditionWithDefaults() *NodeCondition {
	this := NodeCondition{}
	return &this
}

// GetCondition returns the Condition field value
func (o *NodeCondition) GetCondition() Condition {
	if o == nil {
		var ret Condition
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *NodeCondition) GetConditionOk() (*Condition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *NodeCondition) SetCondition(v Condition) {
	o.Condition = v
}

// GetStatus returns the Status field value
func (o *NodeCondition) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NodeCondition) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NodeCondition) SetStatus(v bool) {
	o.Status = v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NodeCondition) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NodeCondition) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *NodeCondition) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *NodeCondition) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *NodeCondition) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *NodeCondition) UnsetMessage() {
	o.Message.Unset()
}

// GetLastHeartbeatAt returns the LastHeartbeatAt field value
func (o *NodeCondition) GetLastHeartbeatAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastHeartbeatAt
}

// GetLastHeartbeatAtOk returns a tuple with the LastHeartbeatAt field value
// and a boolean to check if the value has been set.
func (o *NodeCondition) GetLastHeartbeatAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastHeartbeatAt, true
}

// SetLastHeartbeatAt sets field value
func (o *NodeCondition) SetLastHeartbeatAt(v time.Time) {
	o.LastHeartbeatAt = v
}

// GetLastTransitionAt returns the LastTransitionAt field value
func (o *NodeCondition) GetLastTransitionAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastTransitionAt
}

// GetLastTransitionAtOk returns a tuple with the LastTransitionAt field value
// and a boolean to check if the value has been set.
func (o *NodeCondition) GetLastTransitionAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastTransitionAt, true
}

// SetLastTransitionAt sets field value
func (o *NodeCondition) SetLastTransitionAt(v time.Time) {
	o.LastTransitionAt = v
}

func (o NodeCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["condition"] = o.Condition
	toSerialize["status"] = o.Status
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	toSerialize["last_heartbeat_at"] = o.LastHeartbeatAt
	toSerialize["last_transition_at"] = o.LastTransitionAt
	return toSerialize, nil
}

func (o *NodeCondition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"condition",
		"status",
		"last_heartbeat_at",
		"last_transition_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodeCondition := _NodeCondition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodeCondition)

	if err != nil {
		return err
	}

	*o = NodeCondition(varNodeCondition)

	return err
}

type NullableNodeCondition struct {
	value *NodeCondition
	isSet bool
}

func (v NullableNodeCondition) Get() *NodeCondition {
	return v.value
}

func (v *NullableNodeCondition) Set(val *NodeCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeCondition(val *NodeCondition) *NullableNodeCondition {
	return &NullableNodeCondition{value: val, isSet: true}
}

func (v NullableNodeCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


