/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StripeSetupIntent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StripeSetupIntent{}

// StripeSetupIntent struct for StripeSetupIntent
type StripeSetupIntent struct {
	ClientSecret string `json:"client_secret"`
}

type _StripeSetupIntent StripeSetupIntent

// NewStripeSetupIntent instantiates a new StripeSetupIntent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStripeSetupIntent(clientSecret string) *StripeSetupIntent {
	this := StripeSetupIntent{}
	this.ClientSecret = clientSecret
	return &this
}

// NewStripeSetupIntentWithDefaults instantiates a new StripeSetupIntent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStripeSetupIntentWithDefaults() *StripeSetupIntent {
	this := StripeSetupIntent{}
	return &this
}

// GetClientSecret returns the ClientSecret field value
func (o *StripeSetupIntent) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *StripeSetupIntent) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *StripeSetupIntent) SetClientSecret(v string) {
	o.ClientSecret = v
}

func (o StripeSetupIntent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StripeSetupIntent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_secret"] = o.ClientSecret
	return toSerialize, nil
}

func (o *StripeSetupIntent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStripeSetupIntent := _StripeSetupIntent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStripeSetupIntent)

	if err != nil {
		return err
	}

	*o = StripeSetupIntent(varStripeSetupIntent)

	return err
}

type NullableStripeSetupIntent struct {
	value *StripeSetupIntent
	isSet bool
}

func (v NullableStripeSetupIntent) Get() *StripeSetupIntent {
	return v.value
}

func (v *NullableStripeSetupIntent) Set(val *StripeSetupIntent) {
	v.value = val
	v.isSet = true
}

func (v NullableStripeSetupIntent) IsSet() bool {
	return v.isSet
}

func (v *NullableStripeSetupIntent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStripeSetupIntent(val *StripeSetupIntent) *NullableStripeSetupIntent {
	return &NullableStripeSetupIntent{value: val, isSet: true}
}

func (v NullableStripeSetupIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStripeSetupIntent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


