/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DataPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataPoint{}

// DataPoint Serializer for a single data usage point.
type DataPoint struct {
	Date time.Time `json:"date"`
	Rx int64 `json:"rx"`
	Tx int64 `json:"tx"`
	Total int64 `json:"total"`
}

type _DataPoint DataPoint

// NewDataPoint instantiates a new DataPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataPoint(date time.Time, rx int64, tx int64, total int64) *DataPoint {
	this := DataPoint{}
	this.Date = date
	this.Rx = rx
	this.Tx = tx
	this.Total = total
	return &this
}

// NewDataPointWithDefaults instantiates a new DataPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataPointWithDefaults() *DataPoint {
	this := DataPoint{}
	return &this
}

// GetDate returns the Date field value
func (o *DataPoint) GetDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *DataPoint) GetDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *DataPoint) SetDate(v time.Time) {
	o.Date = v
}

// GetRx returns the Rx field value
func (o *DataPoint) GetRx() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Rx
}

// GetRxOk returns a tuple with the Rx field value
// and a boolean to check if the value has been set.
func (o *DataPoint) GetRxOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rx, true
}

// SetRx sets field value
func (o *DataPoint) SetRx(v int64) {
	o.Rx = v
}

// GetTx returns the Tx field value
func (o *DataPoint) GetTx() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Tx
}

// GetTxOk returns a tuple with the Tx field value
// and a boolean to check if the value has been set.
func (o *DataPoint) GetTxOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tx, true
}

// SetTx sets field value
func (o *DataPoint) SetTx(v int64) {
	o.Tx = v
}

// GetTotal returns the Total field value
func (o *DataPoint) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *DataPoint) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *DataPoint) SetTotal(v int64) {
	o.Total = v
}

func (o DataPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["rx"] = o.Rx
	toSerialize["tx"] = o.Tx
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *DataPoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"rx",
		"tx",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataPoint := _DataPoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataPoint)

	if err != nil {
		return err
	}

	*o = DataPoint(varDataPoint)

	return err
}

type NullableDataPoint struct {
	value *DataPoint
	isSet bool
}

func (v NullableDataPoint) Get() *DataPoint {
	return v.value
}

func (v *NullableDataPoint) Set(val *DataPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableDataPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableDataPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataPoint(val *DataPoint) *NullableDataPoint {
	return &NullableDataPoint{value: val, isSet: true}
}

func (v NullableDataPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


