/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CloudPaymentsPaymentMethodCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudPaymentsPaymentMethodCreateRequest{}

// CloudPaymentsPaymentMethodCreateRequest struct for CloudPaymentsPaymentMethodCreateRequest
type CloudPaymentsPaymentMethodCreateRequest struct {
	Cryptogram string `json:"cryptogram"`
}

type _CloudPaymentsPaymentMethodCreateRequest CloudPaymentsPaymentMethodCreateRequest

// NewCloudPaymentsPaymentMethodCreateRequest instantiates a new CloudPaymentsPaymentMethodCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudPaymentsPaymentMethodCreateRequest(cryptogram string) *CloudPaymentsPaymentMethodCreateRequest {
	this := CloudPaymentsPaymentMethodCreateRequest{}
	this.Cryptogram = cryptogram
	return &this
}

// NewCloudPaymentsPaymentMethodCreateRequestWithDefaults instantiates a new CloudPaymentsPaymentMethodCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudPaymentsPaymentMethodCreateRequestWithDefaults() *CloudPaymentsPaymentMethodCreateRequest {
	this := CloudPaymentsPaymentMethodCreateRequest{}
	return &this
}

// GetCryptogram returns the Cryptogram field value
func (o *CloudPaymentsPaymentMethodCreateRequest) GetCryptogram() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cryptogram
}

// GetCryptogramOk returns a tuple with the Cryptogram field value
// and a boolean to check if the value has been set.
func (o *CloudPaymentsPaymentMethodCreateRequest) GetCryptogramOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cryptogram, true
}

// SetCryptogram sets field value
func (o *CloudPaymentsPaymentMethodCreateRequest) SetCryptogram(v string) {
	o.Cryptogram = v
}

func (o CloudPaymentsPaymentMethodCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudPaymentsPaymentMethodCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cryptogram"] = o.Cryptogram
	return toSerialize, nil
}

func (o *CloudPaymentsPaymentMethodCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cryptogram",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudPaymentsPaymentMethodCreateRequest := _CloudPaymentsPaymentMethodCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloudPaymentsPaymentMethodCreateRequest)

	if err != nil {
		return err
	}

	*o = CloudPaymentsPaymentMethodCreateRequest(varCloudPaymentsPaymentMethodCreateRequest)

	return err
}

type NullableCloudPaymentsPaymentMethodCreateRequest struct {
	value *CloudPaymentsPaymentMethodCreateRequest
	isSet bool
}

func (v NullableCloudPaymentsPaymentMethodCreateRequest) Get() *CloudPaymentsPaymentMethodCreateRequest {
	return v.value
}

func (v *NullableCloudPaymentsPaymentMethodCreateRequest) Set(val *CloudPaymentsPaymentMethodCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudPaymentsPaymentMethodCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudPaymentsPaymentMethodCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudPaymentsPaymentMethodCreateRequest(val *CloudPaymentsPaymentMethodCreateRequest) *NullableCloudPaymentsPaymentMethodCreateRequest {
	return &NullableCloudPaymentsPaymentMethodCreateRequest{value: val, isSet: true}
}

func (v NullableCloudPaymentsPaymentMethodCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudPaymentsPaymentMethodCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


