/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"fmt"
)

// checks if the AccountTokenPair type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountTokenPair{}

// AccountTokenPair Serializer for obtaining JWT tokens using a 16-digit account number.  This serializer validates the provided account number, normalizes it by removing any non-digit characters, and ensures it is exactly 16 digits long. If the account number is valid and corresponds to an existing account, it issues a pair of JWT tokens (refresh and access tokens).  Attributes:     account_number (str): The 16-digit account number.     access (str): The access token issued upon successful authentication.     refresh (str): The refresh token issued upon successful authentication.  Example:     Request:     {         \"number\": \"1234 5678 9012 3456\"     }      Response:     {         \"refresh\": \"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...\",         \"access\": \"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...\"     }
type AccountTokenPair struct {
	Access string `json:"access"`
	Refresh string `json:"refresh"`
	AdditionalProperties map[string]interface{}
}

type _AccountTokenPair AccountTokenPair

// NewAccountTokenPair instantiates a new AccountTokenPair object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountTokenPair(access string, refresh string) *AccountTokenPair {
	this := AccountTokenPair{}
	this.Access = access
	this.Refresh = refresh
	return &this
}

// NewAccountTokenPairWithDefaults instantiates a new AccountTokenPair object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountTokenPairWithDefaults() *AccountTokenPair {
	this := AccountTokenPair{}
	return &this
}

// GetAccess returns the Access field value
func (o *AccountTokenPair) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *AccountTokenPair) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *AccountTokenPair) SetAccess(v string) {
	o.Access = v
}

// GetRefresh returns the Refresh field value
func (o *AccountTokenPair) GetRefresh() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Refresh
}

// GetRefreshOk returns a tuple with the Refresh field value
// and a boolean to check if the value has been set.
func (o *AccountTokenPair) GetRefreshOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Refresh, true
}

// SetRefresh sets field value
func (o *AccountTokenPair) SetRefresh(v string) {
	o.Refresh = v
}

func (o AccountTokenPair) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountTokenPair) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access"] = o.Access
	toSerialize["refresh"] = o.Refresh

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountTokenPair) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access",
		"refresh",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountTokenPair := _AccountTokenPair{}

	err = json.Unmarshal(data, &varAccountTokenPair)

	if err != nil {
		return err
	}

	*o = AccountTokenPair(varAccountTokenPair)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "access")
		delete(additionalProperties, "refresh")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountTokenPair struct {
	value *AccountTokenPair
	isSet bool
}

func (v NullableAccountTokenPair) Get() *AccountTokenPair {
	return v.value
}

func (v *NullableAccountTokenPair) Set(val *AccountTokenPair) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountTokenPair) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountTokenPair) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountTokenPair(val *AccountTokenPair) *NullableAccountTokenPair {
	return &NullableAccountTokenPair{value: val, isSet: true}
}

func (v NullableAccountTokenPair) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountTokenPair) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


