/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingUsage{}

// BillingUsage Serializer for billing usage information including data and device quota.
type BillingUsage struct {
	Data BillingDataQuota `json:"data"`
	Device BillingDeviceQuota `json:"device"`
}

type _BillingUsage BillingUsage

// NewBillingUsage instantiates a new BillingUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingUsage(data BillingDataQuota, device BillingDeviceQuota) *BillingUsage {
	this := BillingUsage{}
	this.Data = data
	this.Device = device
	return &this
}

// NewBillingUsageWithDefaults instantiates a new BillingUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingUsageWithDefaults() *BillingUsage {
	this := BillingUsage{}
	return &this
}

// GetData returns the Data field value
func (o *BillingUsage) GetData() BillingDataQuota {
	if o == nil {
		var ret BillingDataQuota
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BillingUsage) GetDataOk() (*BillingDataQuota, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BillingUsage) SetData(v BillingDataQuota) {
	o.Data = v
}

// GetDevice returns the Device field value
func (o *BillingUsage) GetDevice() BillingDeviceQuota {
	if o == nil {
		var ret BillingDeviceQuota
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *BillingUsage) GetDeviceOk() (*BillingDeviceQuota, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *BillingUsage) SetDevice(v BillingDeviceQuota) {
	o.Device = v
}

func (o BillingUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["device"] = o.Device
	return toSerialize, nil
}

func (o *BillingUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"device",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingUsage := _BillingUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingUsage)

	if err != nil {
		return err
	}

	*o = BillingUsage(varBillingUsage)

	return err
}

type NullableBillingUsage struct {
	value *BillingUsage
	isSet bool
}

func (v NullableBillingUsage) Get() *BillingUsage {
	return v.value
}

func (v *NullableBillingUsage) Set(val *BillingUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingUsage(val *BillingUsage) *NullableBillingUsage {
	return &NullableBillingUsage{value: val, isSet: true}
}

func (v NullableBillingUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


