/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedWalletTransactionList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedWalletTransactionList{}

// PaginatedWalletTransactionList struct for PaginatedWalletTransactionList
type PaginatedWalletTransactionList struct {
	Next NullableString `json:"next,omitempty"`
	Previous NullableString `json:"previous,omitempty"`
	Results []WalletTransaction `json:"results"`
	// Total count of items
	Count *int32 `json:"count,omitempty"`
}

type _PaginatedWalletTransactionList PaginatedWalletTransactionList

// NewPaginatedWalletTransactionList instantiates a new PaginatedWalletTransactionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedWalletTransactionList(results []WalletTransaction) *PaginatedWalletTransactionList {
	this := PaginatedWalletTransactionList{}
	this.Results = results
	return &this
}

// NewPaginatedWalletTransactionListWithDefaults instantiates a new PaginatedWalletTransactionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedWalletTransactionListWithDefaults() *PaginatedWalletTransactionList {
	this := PaginatedWalletTransactionList{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedWalletTransactionList) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedWalletTransactionList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedWalletTransactionList) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *PaginatedWalletTransactionList) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *PaginatedWalletTransactionList) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *PaginatedWalletTransactionList) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedWalletTransactionList) GetPrevious() string {
	if o == nil || IsNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedWalletTransactionList) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedWalletTransactionList) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *PaginatedWalletTransactionList) SetPrevious(v string) {
	o.Previous.Set(&v)
}
// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *PaginatedWalletTransactionList) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *PaginatedWalletTransactionList) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value
func (o *PaginatedWalletTransactionList) GetResults() []WalletTransaction {
	if o == nil {
		var ret []WalletTransaction
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedWalletTransactionList) GetResultsOk() ([]WalletTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedWalletTransactionList) SetResults(v []WalletTransaction) {
	o.Results = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PaginatedWalletTransactionList) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedWalletTransactionList) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PaginatedWalletTransactionList) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *PaginatedWalletTransactionList) SetCount(v int32) {
	o.Count = &v
}

func (o PaginatedWalletTransactionList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedWalletTransactionList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	toSerialize["results"] = o.Results
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

func (o *PaginatedWalletTransactionList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedWalletTransactionList := _PaginatedWalletTransactionList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedWalletTransactionList)

	if err != nil {
		return err
	}

	*o = PaginatedWalletTransactionList(varPaginatedWalletTransactionList)

	return err
}

type NullablePaginatedWalletTransactionList struct {
	value *PaginatedWalletTransactionList
	isSet bool
}

func (v NullablePaginatedWalletTransactionList) Get() *PaginatedWalletTransactionList {
	return v.value
}

func (v *NullablePaginatedWalletTransactionList) Set(val *PaginatedWalletTransactionList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedWalletTransactionList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedWalletTransactionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedWalletTransactionList(val *PaginatedWalletTransactionList) *NullablePaginatedWalletTransactionList {
	return &NullablePaginatedWalletTransactionList{value: val, isSet: true}
}

func (v NullablePaginatedWalletTransactionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedWalletTransactionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


