/*
ForestVPN API

ForestVPN API Documentation

API version: 3.0.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fvpn

import (
	"encoding/json"
	"fmt"
)

// checks if the CloudPaymentsThreeDSecureCompleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudPaymentsThreeDSecureCompleteRequest{}

// CloudPaymentsThreeDSecureCompleteRequest struct for CloudPaymentsThreeDSecureCompleteRequest
type CloudPaymentsThreeDSecureCompleteRequest struct {
	PaRes string `json:"pa_res"`
	AdditionalProperties map[string]interface{}
}

type _CloudPaymentsThreeDSecureCompleteRequest CloudPaymentsThreeDSecureCompleteRequest

// NewCloudPaymentsThreeDSecureCompleteRequest instantiates a new CloudPaymentsThreeDSecureCompleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudPaymentsThreeDSecureCompleteRequest(paRes string) *CloudPaymentsThreeDSecureCompleteRequest {
	this := CloudPaymentsThreeDSecureCompleteRequest{}
	this.PaRes = paRes
	return &this
}

// NewCloudPaymentsThreeDSecureCompleteRequestWithDefaults instantiates a new CloudPaymentsThreeDSecureCompleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudPaymentsThreeDSecureCompleteRequestWithDefaults() *CloudPaymentsThreeDSecureCompleteRequest {
	this := CloudPaymentsThreeDSecureCompleteRequest{}
	return &this
}

// GetPaRes returns the PaRes field value
func (o *CloudPaymentsThreeDSecureCompleteRequest) GetPaRes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaRes
}

// GetPaResOk returns a tuple with the PaRes field value
// and a boolean to check if the value has been set.
func (o *CloudPaymentsThreeDSecureCompleteRequest) GetPaResOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaRes, true
}

// SetPaRes sets field value
func (o *CloudPaymentsThreeDSecureCompleteRequest) SetPaRes(v string) {
	o.PaRes = v
}

func (o CloudPaymentsThreeDSecureCompleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudPaymentsThreeDSecureCompleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pa_res"] = o.PaRes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CloudPaymentsThreeDSecureCompleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pa_res",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudPaymentsThreeDSecureCompleteRequest := _CloudPaymentsThreeDSecureCompleteRequest{}

	err = json.Unmarshal(data, &varCloudPaymentsThreeDSecureCompleteRequest)

	if err != nil {
		return err
	}

	*o = CloudPaymentsThreeDSecureCompleteRequest(varCloudPaymentsThreeDSecureCompleteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pa_res")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCloudPaymentsThreeDSecureCompleteRequest struct {
	value *CloudPaymentsThreeDSecureCompleteRequest
	isSet bool
}

func (v NullableCloudPaymentsThreeDSecureCompleteRequest) Get() *CloudPaymentsThreeDSecureCompleteRequest {
	return v.value
}

func (v *NullableCloudPaymentsThreeDSecureCompleteRequest) Set(val *CloudPaymentsThreeDSecureCompleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudPaymentsThreeDSecureCompleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudPaymentsThreeDSecureCompleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudPaymentsThreeDSecureCompleteRequest(val *CloudPaymentsThreeDSecureCompleteRequest) *NullableCloudPaymentsThreeDSecureCompleteRequest {
	return &NullableCloudPaymentsThreeDSecureCompleteRequest{value: val, isSet: true}
}

func (v NullableCloudPaymentsThreeDSecureCompleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudPaymentsThreeDSecureCompleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


